" First set leader key
let mapleader = ","                             " Use ',' (comma char) as leader key, instead of default '\'
set pastetoggle=<F2>                            " Toggle auto-indenting for code paste
nnoremap <C-J> <C-W><C-J>                       " Move between windows with CTRL-h/j/k/l instead of CTRL-o,h/j/k/l
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <Tab> :bnext<CR>                       " Cycle through tabs
nnoremap <S-Tab> :bprevious<CR>
nnoremap <Leader>w :write<CR>                   " Save file with leader
nnoremap <Leader>q :quit<cr>                    " Quit file with leader
nnoremap <silent> <Leader>/ :nohlsearch<CR>     " Dismiss search highlightedness
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set autoindent
let python_highlight_all = 1
autocmd Filetype python setlocal tabstop=4 shiftwidth=4 expandtab autoindent
" or use ~/.vim/ftplugin/LANGUAGE.vim
set t_Co=256
syntax enable
set ignorecase
set smartcase
set hlsearch
set incsearch
set wrapscan
set fileformat=unix
set encoding=utf-8
set history=500
set timeoutlen=150
set laststatus=2
set scrolloff=5
set hidden
set autoread
set ruler
set backspace=eol,start,indent
set whichwrap+=<,>,h,l,[,]
set splitbelow
set splitright
set lazyredraw
set magic
set showmatch
set matchtime=5
set nojoinspaces
set showcmd
set list listchars=tab:»·,trail:·,nbsp:·
"set cursorline
"set number
set wildmenu
set wildmode=list:longest,full
set wildignore=*.o,*~,*.pyc,*.so,*.zip
set noerrorbells
set visualbell
set t_vb=
set tm=500
