" First set leader key
let mapleader = ","
set pastetoggle=<F2>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>
nnoremap <Leader>w :write<CR>
nnoremap <Leader>q :quit<cr>
nnoremap <silent> <Leader>/ :nohlsearch<CR>

set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set autoindent

" Language specific
let python_highlight_all = 1
autocmd Filetype python setlocal tabstop=4 shiftwidth=4 expandtab autoindent
" or use ~/.vim/ftplugin/LANGUAGE.vim

set t_Co=256
syntax enable
set ignorecase
set smartcase
set hlsearch
set incsearch
set wrapscan
set fileformat=unix
set encoding=utf-8
set history=500
set timeoutlen=150
set laststatus=2
set scrolloff=5
set hidden
set autoread
set ruler
set backspace=eol,start,indent
set whichwrap+=<,>,h,l,[,]
set splitbelow
set splitright
set lazyredraw
set magic
set showmatch
set matchtime=5
set nojoinspaces
set showcmd
"set cursorline
"set number
set wildmenu
set wildmode=list:longest,full
set wildignore=*.o,*~,*.pyc,*.so,*.zip

"set nobackup
"set nowritebackup
"set noswapfile

set noerrorbells
set visualbell
set t_vb=
set tm=500

python << EOF
import os
if 'VIRTUAL_ENV' in os.environ:
  virtualenv_dir = os.environ['VIRTUAL_ENV']
  activate_this = os.path.join(virtualenv_dir, 'bin/activate_this.py')
  execfile(activate_this, dict(__file__=activate_this))
EOF
