---
# REQUIRED external variables:
# websever: apache or nginx
# php: 54, 56, 70 or 71
# pip: yes or no
# rvm: yes or no
- hosts: all
  vars:
    phpmyadmin_url: 'https://files.phpmyadmin.net/phpMyAdmin/4.7.5/phpMyAdmin-4.7.5-english.tar.xz'
    common_pkgs:
      - vim-enhanced
      - mlocate
      - mc
      - wget
      - ftp
      - zip
      - unzip
      - bash-completion
      - bind-utils
      - yum-utils
      - nfs-utils
      - net-tools
      - lsof
      - strace
      - traceroute
      - rsync
    php_pkgs:
      php54:
        - php
        - php-fpm
        - php-cli
        - php-common
        - php-devel
        - php-mysqlnd
        - php-pdo
        - php-pear
        - php-gd
        - php-mcrypt
        - php-mbstring
        - php-tidy
        - php-xml
        - php-xmlrpc
        - php-pecl-redis
        - php-pecl-imagick
      php56:
        - php56u
        - php56u-fpm
        - php56u-cli
        - php56u-common
        - php56u-devel
        - php56u-bcmath
        - php56u-opcache
        - php56u-mysqlnd
        - php56u-pdo
        - php56u-pear
        - php56u-gd
        - php56u-mcrypt
        - php56u-mbstring
        - php56u-tidy
        - php56u-xml
        - php56u-xmlrpc
        - php56u-pecl-igbinary
        - php56u-pecl-imagick
        - php56u-pecl-redis
      php70:
        - php70u-fpm
        - php70u-cli
        - php70u-common
        - php70u-devel
        - php70u-pear
        - php70u-opcache
        - php70u-bcmath
        - php70u-mysqlnd
        - php70u-pdo
        - php70u-json
        - php70u-gd
        - php70u-mcrypt
        - php70u-mbstring
        - php70u-tidy
        - php70u-xml
        - php70u-xmlrpc
        - php70u-pecl-igbinary
        - php70u-pecl-imagick
        - php70u-pecl-redis
      php71:
        - php71u-fpm
        - php71u-cli
        - php71u-common
        - php71u-devel
        - php71u-opcache
        - php71u-bcmath
        - php71u-mysqlnd
        - php71u-pdo
        - php71u-json
        - php71u-gd
        - php71u-mcrypt
        - php71u-mbstring
        - php71u-tidy
        - php71u-xml
        - php71u-xmlrpc
        - php71u-pecl-igbinary
        - php71u-pecl-imagick
        - php71u-pecl-redis
        - pear1u
  become: yes
  tasks:
  - name: Installing ansible helpers
    yum: name={{ item }} state=latest
    with_items:
      - libselinux-python
      - MySQL-python
  - name: Installing YUM helpers
    yum: name={{ item }} state=latest
    with_items:
      - deltarpm
      - yum-cron
      - yum-utils
  - name: Installing Common Packages
    yum: name={{ item }} state=latest
    with_items: "{{ common_pkgs }}"

  - name: Disabling SELinux
    selinux: state=disabled
  - name: Elevating permissions on vagrant home dir
    file: path=/home/vagrant mode=0755
  - name: Creating /home/vagrant/log dir
    file: path=/home/vagrant/log state=directory owner=vagrant group=vagrant mode=0777

  - name: Giving vagrant user custom vimrc
    copy: src=files/vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant mode=0664
  - name: Giving root user custom vimrc
    copy: src=files/vimrc dest=/root/.vimrc owner=root group=root mode=0664

  - block:
    - name: Installing Apache webserver
      yum: name=httpd state=latest
    - name: Removing welcome.conf from Apache
      file: path=/etc/httpd/conf.d/welcome.conf state=absent
    - name: Adding default virtualhost
      copy: src=files/apache_vhost.conf dest=/etc/httpd/conf.d/virtualhost.conf owner=root group=root mode=0644
    when: webserver == 'apache'

  - block:
    - name: Setting Up Nginx repo
      yum_repository:
        name: nginx
        description: Nginx repo
        baseurl: http://nginx.org/packages/centos/7/$basearch/
        gpgcheck: no
    - name: Installing Nginx webserver
      yum: name=nginx state=latest
    - name: Removing default.conf
      file: path=/etc/nginx/conf.d/default.conf state=absent
    - name: Adding default virtualhost
      copy: src=files/nginx_vhost.conf dest=/etc/nginx/conf.d/virtualhost.conf owner=root group=root mode=0644
    when: webserver == 'nginx'

  - name: Installing MySQL RDBMS (MariaDB)
    yum: name={{ item }} state=latest
    with_items:
      - mariadb
      - mariadb-server
  - name: Putting Custom MySQL config
    copy: src=files/my.cnf dest=/etc/my.cnf owner=root group=root mode=0644

  - name: Installing IUS repository
    yum: name=https://centos7.iuscommunity.org/ius-release.rpm state=present
  - name: Installing PHP
    yum: name={{ item }} state=latest
    with_items: "{{ php_pkgs[ 'php' + php | string ] }}"
  - name: Putting customphp.ini
    copy: src=files/customphp.ini dest=/etc/php.d/customphp.ini owner=root group=root mode=0644
  - name: Putting custom php-fpm pool
    copy: src=files/fpm.pool dest=/etc/php-fpm.d/www.conf owner=root group=root mode=0644
  - name: Installing Composer
    get_url: url=https://getcomposer.org/composer.phar dest=/usr/bin/composer owner=root group=root mode=0755
  - name: Installing PHP-FPM files for Apache
    yum: name=php{{ php }}u-fpm-httpd state=latest
    when: webserver == 'apache' and php > 54
  - name: Installing PHP-FPM files for Nginx
    yum: name=php{{ php }}u-fpm-nginx state=latest
    when: webserver == 'nginx' and php > 54
  - name: Nginx config for PHP-FPM status page
    copy: src=files/fpmstatus.nginx dest=/etc/nginx/conf.d/fpmstatus.snip owner=root group=root mode=0644
    when: webserver == 'nginx'
  - name: Apache config for PHP-FPM status page
    copy: src=files/fpmstatus.apache dest=/etc/httpd/conf.d/fpmstatus.conf owner=root group=root mode=0644
    when: webserver == 'apache'

  - name: Downloading PhpMyAdmin
    get_url: url={{ phpmyadmin_url }} dest=/tmp/phpmyadmin.tar.gz
  - name: Extracting PhpMyAdmin
    unarchive: src=/tmp/phpmyadmin.tar.gz dest=/tmp creates=/opt/phpmyadmin
  - name: Moving PhpMyAdmin to /opt/phpmyadmin
    shell: mv /tmp/phpMyAdmin* /opt/phpmyadmin creates=/opt/phpmyadmin
  - name: Installing config.inc.php for phpmyadmin
    copy: src=files/phpmyadmin.config dest=/opt/phpmyadmin/config.inc.php owner=root group=root mode=0644
  - name: Apache config for PhpMyAdmin
    copy: src=files/phpmyadmin.apache dest=/etc/httpd/conf.d/phpmyadmin.conf owner=root group=root mode=0644
    when: webserver == 'apache'
  - name: Nginx config for PhpMyAdmin
    copy: src=files/phpmyadmin.nginx dest=/etc/nginx/conf.d/phpmyadmin.snip owner=root group=root mode=0644
    when: webserver == 'nginx'

  - name: Starting Apache webserver
    service: name=httpd state=started enabled=yes
    when: webserver == 'apache'
  - name: Starting PHP-FPM
    service: name=php-fpm state=started enabled=yes
  - name: Starting Nginx webserver
    service: name=nginx state=started enabled=yes
    when: webserver == 'nginx'
  - name: Starting MySQL service
    service: name=mariadb state=started enabled=yes

  - name: Installing VsFTPd
    yum: name=vsftpd state=latest
  - name: Starting VsFTPd
    service: name=vsftpd state=started enabled=yes

  - block:
    - name: Import gpg key for RVM install
      command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    - name: Disable docs for ruby gems for vagrant user.
      lineinfile:
        dest: /home/vagrant/.gemrc
        line: "gem: --no-document"
        state: present
        create: yes
        owner: vagrant
        group: vagrant
        mode: 0660
    - name: Disable docs for ruby gems for root user.
      lineinfile:
        dest: /root/.gemrc
        line: "gem: --no-document"
        state: present
        create: yes
        owner: root
        group: root
        mode: 0660
    - name: Install RVM
      shell: curl -sSL https://get.rvm.io | bash -s stable creates=/usr/local/rvm/bin/rvm
    when: rvm

  - block:
    - name: Download PIP
      get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/get-pip.py
    - name: Install PIP
      command: python /tmp/get-pip.py creates=/usr/bin/pip
    when: pip
