---
- name: Import gpg key for RVM install
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- name: Disable docs for ruby gems for vagrant user.
  lineinfile:
    dest: /home/vagrant/.gemrc
    line: "gem: --no-rdoc --no-ri"
    state: present
    create: yes
    owner: vagrant
    group: vagrant
    mode: 0660
- name: Disable docs for ruby gems for root user.
  lineinfile:
    dest: /root/.gemrc
    line: "gem: --no-rdoc --no-ri"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0660
- name: Install RVM
  shell: curl -sSL https://get.rvm.io | bash -s stable creates=/usr/local/rvm/bin/rvm
